name: Shared Docker Action
description: Shared stapes for build push Docker image

inputs:
  github_token:
    description: GitHub token for GHCR login
    required: false
  context:
    description: Dockerfile path
    required: true
  push:
    description: load data to varify 
    required: false
    default: 'false'
  tag_prifix:
    description: Prefix for the Docker image tags
    required: true
  dockerfile:
    description: Path to the Dockerfile relative to the context
    required: true
  
  

runs:
  using: "composite"
  steps:
    - name: Code CheckOut
      uses: actions/checkout@v4

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get Docker directory name
      id: docker_dir
      shell: bash
      run: |
        dockerfile_path="${{ inputs.dockerfile }}"
        docker_dir=$(dirname "$dockerfile_path")
        # Remove trailing slash if any
        docker_dir="${docker_dir%/}"
        echo "name=$(basename "$docker_dir")" >> "$GITHUB_OUTPUT"

    - name: Login to GHCR
      if: inputs.push == 'true'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{inputs.github_token}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ${{inputs.context}}
        file: ${{ inputs.dockerfile }}
        push: ${{inputs.push}}
        load: ${{ inputs.push != 'true' }}
        tags: ${{inputs.tag_prifix}}-${{ steps.docker_dir.outputs.name }}:latest