name: Api Build-Push docker image

on:
  push:
    paths:
      - 'api/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build and deploy maually'
        required: false
        default: 'main'
        
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code CheckOut
        uses: actions/checkout@v4

      - name: Use Common Action For Build
        id: Shared_Build 
        uses: ./.github/actions/shared-build
        with:
          context: ./api
          dockerfile: api/Dockerfile
          tag_prifix: ghcr.io/rajarshi2441139/devops-qr-code
          push: "false"
  
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          file: api/Dockerfile
          push: true
          tags: ghcr.io/rajarshi2441139/devops-qr-code-api:release-${{ github.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
